# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# split panes using v and h
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# Configure powerline
source "/usr/share/powerline/bindings/tmux/powerline.conf"

# change tmux pane movement bindings to be similar to vim [hjkl]
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Enable mouse control (clicable windows, panes, resizable panes)
set -g mouse on

# enable ctrl+a a to move cursor to the beginning of the line in bash
bind a send-prefix

# toggle synchronize-panes
bind e setw synchronize-panes

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Enable auto-session save and restore, even across restarts
#set -g @plugin 'tmux-plugins/tmux-resurrect'
#set -g @plugin 'tmux-plugins/tmux-continuum'

#set -g @continuum-restore 'on'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
